### ISSUE TITLE
AttributeError: inlet_utility_stream

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#20]
**Describe the bug**
I found this bug when designing HXs, I wasn't sure if it was due to my codes or biosteam, but then I found the same bug existed in the cornstover biorefinery. The `heat_utilities` attribute works for some units but not for others. I'm not sure whether it's from biosteam or biorefineries.

**To reproduce**
```python
from biorefineries.cornstover.system import *
# This works
R301.heat_utilities

# But this won't work
BT.heat_utilities
```

**Screenshots**
<img width="550" alt="Screen Shot 2020-04-06 at 3 51 24 PM" src="https://user-images.githubusercontent.com/49011373/78603930-91e0c400-781e-11ea-8b47-f4515fea0d5d.png">

**Environment**
 - Python: v3.7.6
 - OS: macOS Catalina 10.15.3
 - BioSTEAM: v2.11.0
 - thermosteam: v0.9.0
 - biorefineries: v2.8.0

**Comment by yoelcortes** [comment]
Seems like there is a bug in the representation of the heat utility. For now you can still use the heat utilities, but you won't be able to see the heat utilities of the boiler turbogenerator.

I'll make sure to patch this up soon. Thanks!

**Comment by yalinli2** [comment]
No problem, it actually wasn't affecting anything now, I found this accidentally, thanks!!!

**Comment by yalinli2** [comment]
Oh BTW, when fixing this, you may also want to have a look at the `save_report` function, it cannot export the diagram, but `diagram(kind='thorough')` works fine.

**To reproduce**
```python
from biorefineries.lipidcane.system import lipidcane_sys
# This generates the thorough diagram
lipidcane_sys.diagram(kind='thorough')
# This generates a report without the diagram
lipidcane_sys.save_report('lipidcane_sys.xlsx')
```


**Screenshots**
<img width="550" alt="Screen Shot 2020-04-06 at 6 04 12 PM" src="https://user-images.githubusercontent.com/49011373/78613294-09b7ea00-7831-11ea-8263-050b3537c3ba.png">

**Comment by yoelcortes** [comment]
Thanks for reporting. Both issues have been taken care of on github. The PyPI version will be released next week with a few other updates.

**Comment by yalinli2** [comment]
I saw you fixed the inlet_utility_stream issue by using the `reverse` function to take the "reverse" of the mixture of all steam utilities in the system, which means that all steam utilities in the system have to be the same kind of steam - is this what should be happening in the reality?

Also, you may want to fix the SteamMixer in the cornstover biorefinery, it has the same inlet_utility_stream issue as for BT. Can you explain a bit about this issue - I'm not sure what caused this and how what you did was able to fix it.

Finally, about the `regeneration_price` and `transfer_price` of `UtilityAgent`, if the biorefinery has BT/CT to generate the steam and we consider the CAPEX and OPEX of BT/CT, should these prices be 0 (which seems to be the case for the cooling agent `cooling_water` of cornstover biorefinery but not for the heating agent `low_pressure_steam`)?

Thanks @yoelcortes !!!

**Comment by yoelcortes** [comment]
1. The `<HeatUtility>.reverse` method just makes it so that instead of consuming a utilitity, it is producing a utility (or vice versa). You may have noticed I run the `<HeatUtility>.mix_from` method first to find the steam demand from all HeatUtility objects that use steam. To use the `mix_from` method, all heat utilities must use the same agent. This is because a HeatUtility object can only contain one agent.

2. Ahh, yeah thats a bug. The `<BoilerTurbogenerator>.steam_utilities` contains all steam utilities of the process, including the one from the SteamMixer, so it makes sense that we see the same issue.

3. Although steam is being generated, it is possible that the generated steam does not meet the biorefinery demand (in extreme cases). So it makes sense to add price. Other alternatives include adding natural gas to the boiler. Note that the cost of the steam demand is substracted by the steam generated. So if the generated steam meets the demand, its as if the price of steam is zero. As for the cooling water and chilled water, these can be produced at any rate, so its ok to have the price be zero.

**Comment by yalinli2** [comment]
All sounds great! Only one question for point 1: in reality, is it possible for a boiler to produce different types of steams? i.e., to let the BT unit have multiple `HeatUtility` objects.

The Humbird BT generates both low pressure steam and high pressure steam, but I saw you only used low pressure steam in the cornstover design.

Thanks!!!

**Comment by yoelcortes** [comment]
Certainly possible, but I don't see any advantage in terms of the results. The boiler-turbogenerator is not a rigorous one, so in the end it won't matter what kind of steam you produce.

**Comment by yalinli2** [comment]
Got it, thanks!!!
