### ISSUE TITLE
Feature Request: continue model evaluation when system runs into simulation error for certain parameters

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#24]
**Description**
Currently, if we are doing Monte Carlo evaluation for 5000 scenarios and unfortunately the system runs into some error during the last simulation, BioSTEAM will reports an error and won't return results, I've run into this a couple of times... 😢 

So I'm wondering if it is possible to:
1. Let BioSTEAM continue the evaluation (since the next set of scenario parameters might not lead to error).
2. When generating the result table, save 'NA' or similar for the failed simulation.
3. Save the error message somewhere for later debugging.

I think it's doable using `try:... except:...`, but I'm not sure whether using `try:... except:...`is good. This change might require some tweaks for `spearman` evaluation as well. However the change can be very helpful if the designed system is not very robust, or some combination of parameters are just bad.

Thanks in advance for considering!

**Comment by yoelcortes** [comment]
Hi Yalin, I have run into errors when evaluating Monte Carlo. It usually means that the system is not robust  (i.e. accumulation of energy/material in streams), or going to an infeasible region (the conversions are too high or something). One problem with using try and exceptions is that information from the last run still lingers and causes a cascade of infeasible scenarios. This could be fixed by resetting all flows each time a system fails. However, if the system is not robust, you could be getting significantly different results for very similar scenarios when you reset flows.

I think you could add the try and except blocks in the `<Model>.evaluation` method (lines 145, 146) and see what you get:
```python
try: 
    simulate()
except:
    self._system.reset_flows()
    values[i] = [None] * len(funcs)
else:
    values[i] = [i() for i in funcs]
```
I'd be willing to make this can be an optional behavior in BioSTEAM if you'd like to make a pull request ;)

Alternatively, you could run each sample in the model outside the evaluate method:
```python
for i in samples:
    # Some debugging stuff or, save data
    results_dict = model(i)
```
If you still can't find where the system is failing I'd be happy to help you out too.

**Comment by yalinli2** [comment]
A quick followup that just adding the try/except block won't work (because all flows are set to 0, it leads to divide by 0 error when simulating stream price for TEA). So I think I'll work around this for now. But it's good to know the `reset_flows` method, would save me a lot of time (I used to restart the kernel every time to de-cache)

However this leads to some additional questions:
1. When using `<Model>.evaluate`, does it retain the system's setting on converge_method, maxiter, and molar_tolerance?
2. If I let my system simulate for five times within the system.py, when executing `<Model>.evaluate`, for each scenario, will my system be simulated for only once or six times?

Thanks!

**Comment by yoelcortes** [comment]
Hmm, the streams should have a flow after simulating again... Could one of your products not be updated by simulating the system? As for your numbered questions:
1. Yes, all settings are kept.
2. The system is only simulated once in each scenario. If your results are changing significantly, with resimulating the system, there may be a problem in one of your units (energy or mass balance). If you send me the files, I can help you debug it.

**Comment by yalinli2** [comment]
Thanks for answering my question!

As for the try/except thing, I tried to manually reset my system flows and re-simulate and it worked, so I'm not sure what exactly happened, but I made a couple of changes since that so those might have helped. The unfortunate (or fortunate) thing is that I can run Monte Carlo without getting errors for small trials, so I'll close this for now and maybe revisit when I ran into the problem again, thanks!
