### ISSUE TITLE
Select a liquid/gas stream of a rigorously simulated HXutility unit

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#26]
**Description**
Suppose I want to simulate a HXutility as follows:
```python
import thermosteam as tmo
from biosteam.units import StorageTank, HXutility

chemicals = tmo.Chemicals(['Water', 'Ethanol'])
tmo.settings.set_thermo(chemicals)

s1 = Stream('s1', Water=100, Ethanol=50)
H1 = HXutility('H1', ins=s1, V=0, rigorous=True)
H1.show() # before simulation
H1.simulate()
H1.show() # after simulation
```
<img width="337" alt="Screen Shot 2020-05-29 at 7 53 51 AM" src="https://user-images.githubusercontent.com/49011373/83261817-958b2a00-a181-11ea-95be-e7158f8a42c2.png">

My question is, how can I select the liquid phase of H1 outs as the ins for a downstream unit? Note that before simulation, H1.outs[0] is a `Stream`, not a `MultiStream`, so doing:
```python
s1 = tmo.Stream('s1', Water=100, Ethanol=50)
H1 = HXutility('H1', ins=s1, V=0, rigorous=True)
H1_liquid = tmo.Stream('H1_liquid', phase='l')
H1_liquid.mol = H1.outs[0].imol['l']
T1 = StorageTank('T1', ins=H1_liquid)

from biosteam import System
system = System('system', path=(H1, T1))
```

raises error:
<img width="538" alt="Screen Shot 2020-05-29 at 7 59 54 AM" src="https://user-images.githubusercontent.com/49011373/83262363-76d96300-a182-11ea-9235-81efe22a7155.png">

_Also, it is strange to me that the outs of H1 after simulation is at 354.39K - I thought it should remain at 298.15K as the ins?_

Thanks!!!

**Environment**
OS: macOS Catalina 10.15.4
Python: v3.7.6
biosteam: v2.17.7
thermosteam: v.0.17.15

**Comment by yoelcortes** [comment]
Yeah, currently tanks cannot handle multi streams unfortunately. For now, I would suggest not use rigorous = True if the outlet is connected to a tank.

The argument `V` denotes the vapor fraction. If rigorous is True, VLE is performed and that temperature you see is the bubble point temperature. If you'd like to hit a target temperature, just specify `T` instead of `V`.

I think what you are looking for is to use HXutility with rigorous=False and set V=0 and T=298.15. When rigorous is false, VLE is not performed.

**Comment by yoelcortes** [comment]
For the next update, I'll try to make it possible for storage tanks to handle multiple phases and for rigorous heat exchangers to not conver a Stream to a MultiStream when the vapor fraction or temperature dictates that only one phase exists (i.e. not within the bubble and dew point). Thanks!

**Comment by yalinli2** [comment]
Thanks for looking into this! Updating HX would be great!

A follow-up question for HXutility setting, in below:
<img width="546" alt="Screen Shot 2020-05-30 at 6 46 38 AM" src="https://user-images.githubusercontent.com/49011373/83327428-56bca900-a241-11ea-9c3a-58118aedf01f.png">

When I didn't set T, outs of `H1` is defaulted to 298.15K, why should this be? I can set the temperature as in the case of `s2`, but what if I don't know the temperature of `s1` (and it can be changing)? I thought it'd be better to retain the temperature of ins?

Thanks!!!

**Comment by yoelcortes** [comment]
The current code doesn't change outlet temperature if no T is given (it was 298.15 to begin with). You can add a process specification or subclass from HXutility to add your own custom behavior. In either case (copying the inlet temperature or not changing outlet stream temperature), the outlet temperature would be wrong. The temperature of the outlet stream cannot stay the same when condensing various chemicals. I would rather make it so that the user must specify the outlet temperature.

**Comment by yalinli2** [comment]
Sounds great, thanks!!!
