### ISSUE TITLE
FeatureRequest: Clear cache and retry for failed evaluation

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#34]
**Description**
First, thanks for adding the _failed_evaluation function!

I found that doing evaluation for my system, there's a certain Monte Carlo sample that won't trigger any error if I just run this sample, but the system won't be able to converge if this sample is run in evaluation, and I suspect it's because of the cache of other samples run before this one, as my system includes multiple distillation columns.

For the following codes for bst.evaluation._model:
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/d34c533f09e6791ae635794656c8e5696de08026/biosteam/evaluation/_model.py#L162-L166

I changed to:
```python
try:
    self._system.simulate()
    return [i() for i in self._getters]
except:
    try:
        self._system.empty_recycles()
        self._system.empty_process_streams()
        for i in self._system.units:
            if hasattr(i, '_McCabeThiele_args'):
                i._McCabeThiele_args[:] = 0 # clear the cache for distillation columns 
        self._system.simulate()
        return [i() for i in self._getters]
    except:
        return self._failed_evaluation()
```
And it solved the problem. Though because this clears the cache, results for samples after this one changed 1-2%. However I don't think this is a big deal.

**Proposed Feature**
So I'll propose for all units that use cache to speed up simulation, we add a `clear_cache` function. Then for the system, we also add a `clear_system_cache` function to call the clear_clear function of those units. In evaluation, if it fails, we first check if clearing cache and process streams/recycles can solve this.

**Additional Notes**
Since BioSTEAM now allows failed evaluation, another feature that'll be good is to print a summary at the end of evaluation to show how many simulations are good and how many fail - I didn't notice the failed evaluation at first.

Also, for the failed metrics, now they are recorded as `nan`, so spearman results can't be calculated. However for my particular case, I ran 100 samples and only 1 failed, so I think calculating Spearman's rho for the 99 good samples still make sense. So I'm wondering if we can exclude the failed samples in Spearman calculation?

Thanks a lot!!!

**Environment**
Python: v 3.7.6
BioSTEAM: v 2.20.9

**Comment by yoelcortes** [comment]
Sounds good, the proposed feature is pretty much how we would get it done in BioSTEAM. 

As for Spearman correlation, I'll expose the <Model>.table attribute so that people can do things like:

```python
model.table = model.table.dropna()
```

Pandas has some excellent methods for data cleaning, so I think leaving this up to the user would be better than adding more optional behaviors that may slow down methods in biosteam.

Thanks!

**Comment by yalinli2** [comment]
Sounds good and I agree on letting users clean up the data! I'll leave this issue open until we have the `clear_cache` function in BioSTEAM, but you can close it now if you have it on a separate TODO list, thanks!

**Comment by yoelcortes** [comment]
I made a couple of updates to the repository:

1. Add a reset_cache method to unit operations and system objects.
2. <Model>.table attribute can now be set.
3. Model spearman method can now take parameters. So <Model>.spearman(metrics=None) is now <Model>.spearman(parameters=None, metrics=None)... You might get a bug due to the change in signatures.
4. The spearman table uses multiindices just like the <Model>.table attribute. We can now do things like:
  ```python
  >>> rhos = model.spearman(parameters, metrics)
  >>> rhos[metrics[0].index] # -> metric rhos for all parameters
  >>> rhos.loc[parameters[0].index] # -> parameter rhos for all metrics
  ```
 
Could you test it out for any bugs? Once its tested, I'll make upload it to PyPI.

Thanks!

**Comment by yalinli2** [comment]
Sure! Testing now!

**Comment by yalinli2** [comment]
Errr I think you forgot to ask the system to re-simulate after clearing the cache? Otherwise it works fine!

**Comment by yoelcortes** [comment]
Gotcha, just fixed that, can you test again? Thanks!

**Comment by yalinli2** [comment]
All works well! Thanks for updating this so quickly!
