### ISSUE TITLE
diagram printing streams

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#42]
Why want to print these streams? Was that legacies from debugging or serving special purpose? Thanks!

https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/4e1da33075b7de56600004dd79d2eb1f46a842b2/biosteam/digraph/digraph.py#L186

https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/4e1da33075b7de56600004dd79d2eb1f46a842b2/biosteam/digraph/digraph.py#L205

**Comment by yoelcortes** [comment]
Good catch! I added a warning for units with connections that do not have graphics settings

**Comment by yalinli2** [comment]
Yep thanks for adding the warning, for my system, it reads:
```
/Users/yalinli_cabbi/OneDrive/Coding/biosteam/biosteam/_graphics.py:56: GraphicsWarning: inlet #2 at <Mixer: A9> missing graphics options; UnitGraphics object expected at most 2 inlets
  options = {'headport': 'c'}
```

But I'm not sure where I did wrong. A9 is a subclass of `bst.Mixer` with 5 influents, why biosteam would only expect 2 inlets? The system can be simulated without a problem.

I found that `A9._graphics.edge_in` is a list of 2 (`[{'headport': 'c'}, {'headport': 'c'}]`), but I'm not sure when the `edge_in` value was set. 

Also, it'll be great if the warning message can be more clear. I'm not sure how I can add graphic options (I'm not even sure what is graphic options), and it didn't explain why UnitGraphics object is expected for at most 2 inlets. Thanks!!!

**Comment by yoelcortes** [comment]
Thanks for reviewing the change! Here are some notes before I get to explaining some fixes I just made:

* The location at which streams come in and out of unit operations (in diagrams) are set using dictionaries provided by the `edge_in` and `edge_out` attributes of the UnitGraphics object (the `_graphics` attribute of Unit objects). 

* The UnitGraphics object is automatically initialized whenever you subclass from Unit and don't provide your own `_graphics` class attribute. 

* When you subclass from Mixer, a new UnitGraphics object is initialized as well. Because the `_N_ins` of a Mixer is 2, it only expects at most two inlets streams.

The warning is not too helpful, and it shouldn't be issued since the number of inlets is not fixed. The warning should only be raised in the occasion that you created your own UnitGraphics object and forgot to include the right number of options in `edge_in` and `edge_out`.

I fixed it so that you don't get the warning and the changed the warning to say something like:
```
GraphicsWarning: inlet #{sink_index} at {repr(sink)} missing graphics options; expected at most {N_inlets} inlets
```

Hope this helps,
Feel free to reopen the issue if anything ;)

**Comment by yalinli2** [comment]
Ah I see! Indeed the warning was raised before because the subclass I made did not have fixed _N_ins and _N_outs. Now the warning is no longer there, thanks!
