### ISSUE TITLE
Modify heat_exchanger_utilities_from_units

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#46]
In the following code:

https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/cca6df548b22c7bbbde10fae68f730f832485355/biosteam/process_tools/utils.py#L43

Will it be better to change to:
```python
return [i for i in heat_utilities if i.heat_exchanger and i.duty != 0]
```

The original one will cause problem in HXN if there's no duties associated with a `HeatUtility`, because this line:
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/cca6df548b22c7bbbde10fae68f730f832485355/biosteam/units/facilities/hxn/hxn_synthesis.py#L99

will raise an error since `hu.heat_exchanger.ins[0]` is a MissingStream, it doesn't have T

Thanks!

**Comment by yoelcortes** [comment]
Thanks, Yalin. I added line 124 to the _heat_exchanger_network.py module:

hx_utils = [i for i in hx_utils if i.duty]

Hopefully this fixes your problem. I left the biosteam.process_tools.utils.py file the same because function should still retrieve heat utilities even if unit operations haven't run (and utilities are zero).

Thanks!

**Comment by sarangbhagwat** [comment]
Thanks Yalin and Yoel!

Yoel, hope that line was added to my updated version of HXN!

Sarang

**Comment by yalinli2** [comment]
Ah agree that should leave the biosteam.process_tools.utils.py unchanged, and adding `hx_utils = [i for i in hx_utils if i.duty]` fixes the problem, thanks!
