### ISSUE TITLE
Feature Request: An argument that lets clustered PFDs know which unit should be first in each cluster

### ISSUE THREAD

**Issue by sarangbhagwat** [BioSTEAMDevelopmentGroup/biosteam#48]
The new option to "cluster" units that are in the same recycle systems in a process flow diagram is really cool! I think it would be even more useful if we could pass an argument for which unit should be first (on the left-most part) in each cluster. That way, e.g., in SYS3 of the sugarcane to 3-HP biorefinery flowsheet below, we could have Cofermentation be the “first” unit in the SYS3 cluster to make the process clearer at first glance.

![deleteme_sugarcane_HP](https://user-images.githubusercontent.com/59667492/103338097-e7ab6b00-4a42-11eb-9098-efb04b5feb91.png)

**Comment by yoelcortes** [comment]
I'd be open to add some functions in biosteam to allow users modify diagrams (including setting relative position of units). However, this is may be hard to do in graphviz (considering we let graphviz optimize node positions). I don't have any plans on working on this, but feel free to take a shot at it if you have some time:

https://graphviz.readthedocs.io/en/latest/

Thanks!

**Comment by yoelcortes** [comment]
@sarangbhagwat I thought about why is the order of the unit operations so crazy and figured out that we can get better diagrams if the unit nodes are created in the same order as in the path, (this was not the case previously). Graphviz places the units left to right, then goes through some optimization algorithm so that streams (edges) do not crossover and node distances are pretty. Here are the "cluster" and "thorough" diagrams that we get with the new updates:

![image](https://user-images.githubusercontent.com/29529649/103376743-1c4f0f00-4aa3-11eb-90ea-b7f4e6e0d024.png)


![image](https://user-images.githubusercontent.com/29529649/103376523-7b605400-4aa2-11eb-8800-98a485531cae.png)


Hope this helps in the meanwhile!

**Comment by sarangbhagwat** [comment]
Nice! Looks like this solves the issue. Thanks!!
