### ISSUE TITLE
Solve_price does not work when the product stream has an initial price of np.nan

### ISSUE THREAD

**Issue by sarangbhagwat** [BioSTEAMDevelopmentGroup/biosteam#63]
**Describe the bug**
Initial value of np.nan for a product stream prevents solve_price() from working. When running analyses with infeasible regions in a given solution space, product price may often be set to np.nan as this is the value that solve_price will return for those points.

**To Reproduce**
After running any biorefinery in Bioindustrial-Park, run the following two lines:

><product_stream>.price = np.nan
>  <TEA_object>.solve_price(<product_stream>)

**Expected behavior**
Output: the solved price of the product.

**Actual behavior**
Output:
> np.nan

**Version**
I would have pushed changes myself, but I'm currently working on the HP biorefinery which at present requires a previous version of BioSTEAM, and so would prefer not to pull the current version. I believe the problem is common to both versions, so we can fix this for the current version (2.31.1).

**Potential Solution**
The code for _tea is different for v2.31.1 from the HP version, so I cannot currently confirm that this will work, but the idea is to use np.nan_to_num to convert any nan values in either sales or market_value. 

In _tea.py, inside the definition for market_value on line 716, replace

> return stream.cost * self.operating_hours

with

> return np.nan_to_num (stream.cost * self.operating_hours)

An alternative, potentially uglier solution could be to make solve_price return (very) large values rather than np.nan.

**Comment by yoelcortes** [comment]
Thanks for posting this issue! It is fixed with #587c4d3. The method now attempts to solve the price with an initial guess of 0 if the first attempt (using the original price) did not work. The method is more robust and should find solution for any problem, but in the unexpected case it could not, an error will be raised. Also, in thermosteam, stream prices must now be finite, so any bugs with prices will not propagate.
