### ISSUE TITLE
system.get_electricity_consumption() unit

### ISSUE THREAD

**Issue by joyxyz1994** [BioSTEAMDevelopmentGroup/biosteam#71]
Hey @yoelcortes, is `system.get_electricity_consumption()` supposed to return a value in MWh/yr? The documentation says 'MW'. I'm a little confused. Thanks!

**Comment by yalinli2** [comment]
Thanks Yoel for fixing it, but is it good to just change from MW·hr/yr to kW·hr/yr? This could potentially change a lot of calculation results, thanks!

**Comment by yalinli2** [comment]
To be honest I can't recall whether I've used other in one case in a tutorial. Staying in MWh/yr would be safe, but changing to kWh/yr would be more straightforward to new users (who haven't read the documentation) since at the unit level it's kWh/hr (but for duties staying in kJ would probably make the number really large). So I'm OK either way, but if we want to change, it should be now.

Thanks!
