### ISSUE TITLE
No error in making a diagram when Graphviz is not installed.

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#75]
No specific code I can provide since it was not on my computer. So I will just describe it.

When the graphviz Python library is installed, but the Graphviz is not, the attempts to build a diagram do not work and do not raise any errors.

While if you try to use the graphviz functions that are used in biosteam outside running biosteam, the error is raised.

I would propose to take it into account and raise this error if the diagram method is used for the Unit class.

**Comment by yalinli2** [comment]
Hi Dmitry, this is because now that import `biosteam`, `biosteam.RAISE_GRAPHVIZ_EXCEPTION` is defaulted to `False`, if you change that to `True`, `biosteam` will raise the error.

However, I agree with you that it makes it hard for users to figure out why they can't get the diagrams (took me a while to figure out). So @yoelcortes , maybe we can issue a warning if there's a problem with `graphviz`? This way at least the users will know, thanks!

**Comment by yoelcortes** [comment]
Thanks for noting this, Dmitry! I'll add a warning, good idea Yalin. It will take a couple of days before the PyPI version with the warning is released.

**Comment by yalinli2** [comment]
Coolio! Thanks Yoel!

**Comment by DmitryBachin** [comment]
Thanks, Yoel and Yalin!
