### ISSUE TITLE
Using production and consumption keys for bst.Power_Utility.get_impact()

### ISSUE THREAD

**Issue by dstew16** [BioSTEAMDevelopmentGroup/biosteam#76]
Hi Yoel,

With one of your recent commits named 'add lca support for agile systems', you removed the ability to specify both a production and consumption key for LCA using the `get_impact` method for the bst `Power_Utility` object. I had been making use of that feature, because I'm assuming different CF's for electricity production and consumption in my work, so I was wondering if there was a particular reason you changed the code and/or if it's possible to change it back to using two keys.

Please let me know, thanks!
Dalton

**Comment by yoelcortes** [comment]
Hi Dalton, 

Sorry! I did not realize this was being used. I removed it because it because there were some system-wide features that are not yet compatible with it (because they only accept one impact key). But looking back, yeah, we should definitely keep this feature. I will add it back once as soon as I get the system-wide features working with it, which should take about an hour.

Thanks!

**Comment by yoelcortes** [comment]
@dstew16, I made changes to allow different characterization factors for net consumption and production of electricity with a single impact key. So this is now possible:

```python
>>> import biosteam as bst
>>> key = 'GWP'
>>> bst.PowerUtility.set_CF(key, consumption=0.11, production=0.1)
>>> pu = bst.PowerUtility(consumption=1)
>>> pu.get_impact(key)
0.11
>>> pu.production = 2
>>> pu.get_impact(key)
-0.1
```

If you'd like to use different keys for production and consumption, you can make biosteam backwards compatible with the following code:

```python
from biosteam import PowerUtility
def get_impact(self, consumption_key=None, production_key=None):
        """Return the impact in impact / hr given characterization factor keys 
        for consumption and production. If no production key given, it defaults
        to the consumption key."""
        rate = self.consumption - self.production
        if rate > 0.:
            if consumption_key is None: consumption_key = production_key
            cf = self.characterization_factors[consumption_key]
            if isinstance(cf, tuple): cf = cf[0]
            return cf * rate
        else:
            if production_key is None: production_key = consumption_key
            cf = self.characterization_factors[production_key]
            if isinstance(cf, tuple): cf = cf[1]
            return cf * rate
PowerUtility.get_impact = get_impact
```

I recommend changing the code to use one impact key (instead of changing the get_impact method to use different consumption/production keys) because then you can use features of System objects to create tables.

Hope this helps!
